version: '3'

volumes:
  postgres_data:
  pgadmin:


networks:
  microservices:
    external:
      name: laradock_backend

services:
  server_app:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: server-app
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./src/app-blog:/var/www/app-blog
      - ./docker/nginx/pelni.conf:/etc/nginx/conf.d/default.conf
    networks:
      - microservices
    working_dir: /var/www

  workspace_app:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    container_name: workspace-app
    restart: always
    volumes:
      - ./src:/var/www
    networks:
      - microservices
    working_dir: /var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres_app
      - DB_PORT=5432
      - DB_DATABASE=blog
      - DB_USERNAME=cabe2cabean214@gmail.com
      - DB_PASSWORD=SuperSecret

  postgres_app:
    image: postgres
    container_name: postgres-app
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - microservices
    environment:
      - POSTGRES_USER=cabe2cabean214@gmail.com
      - POSTGRES_PASSWORD=SuperSecret

  pgadmin4_app:
    image: dpage/pgadmin4
    container_name: pgadmin4-app
    restart: always
    ports:
      - 5050:80
    networks:
      - microservices
    depends_on:
      - postgres_app
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=cabe2cabean214@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret

  adminer:
    image: adminer
    container_name: adminer-app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres_app
    networks:
      - microservices
    environment:
      - ADMINER_DEFAULT_SERVER=postgres_app
      - ADMINER_DESIGN=pepa-linha
