version: '3.8'

services:

  # app service
  app:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    container_name: php-fpm_achtarudin
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www
    networks:
      - backend

  # nginx service
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx_achtarudin
    restart: always
    ports:
      - 8000:80
      - 4430:443
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d 
    networks:
      - backend
    working_dir: /var/www

networks:
  backend:
