version: '3'

services:

  # app service
  app:
    build:
      context: ./php-fpm
      dockerfile: Dockerfile
    container_name: php-fpm_achtarudin
    restart: always
    working_dir: /var/www
    volumes:
      - ../src:/var/www
    networks:
      - microservices

  # nginx service
  nginx:
    image: nginx:1.19-alpine
    container_name: nginx_achtarudin
    restart: always
    ports:
      - 8000:80
      - 4430:443
    volumes:
      - ../src:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - microservices
    working_dir: /var/www

networks:
  microservices:
    external:
      name: laradock_backend
